// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh9CgTyDGA-MTbEtAUQ2RUp2uU3gKYbas',
    appId: '1:695705733227:web:c93d93065c8e842a7f092e',
    messagingSenderId: '695705733227',
    projectId: 'chat-app-f34d5',
    authDomain: 'chat-app-f34d5.firebaseapp.com',
    storageBucket: 'chat-app-f34d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa6U1GTp8teLoxGciJjDiOi8mUoJnOzRY',
    appId: '1:695705733227:android:3ded79865b803fc87f092e',
    messagingSenderId: '695705733227',
    projectId: 'chat-app-f34d5',
    storageBucket: 'chat-app-f34d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5GT8S3BnhDnyDlXl4dOIpKLsyx8rKUcM',
    appId: '1:695705733227:ios:90c27c8d8094712a7f092e',
    messagingSenderId: '695705733227',
    projectId: 'chat-app-f34d5',
    storageBucket: 'chat-app-f34d5.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5GT8S3BnhDnyDlXl4dOIpKLsyx8rKUcM',
    appId: '1:695705733227:ios:90c27c8d8094712a7f092e',
    messagingSenderId: '695705733227',
    projectId: 'chat-app-f34d5',
    storageBucket: 'chat-app-f34d5.appspot.com',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh9CgTyDGA-MTbEtAUQ2RUp2uU3gKYbas',
    appId: '1:695705733227:web:4c216d7ee319dfec7f092e',
    messagingSenderId: '695705733227',
    projectId: 'chat-app-f34d5',
    authDomain: 'chat-app-f34d5.firebaseapp.com',
    storageBucket: 'chat-app-f34d5.appspot.com',
  );
}
